/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/-/user": {
    get: operations["get_users"]
    post: operations["create_user"]
  }
  "/v1/-/user/{uuid}": {
    get: operations["get_user"]
  }
}

export interface components {
  schemas: {
    User: {
      uuid?: string
      email?: string
      first_name?: string
      last_name?: string
      date_of_birth?: string
      email_verified?: boolean
      phone_verified?: boolean
      identity_verified?: boolean
      password_hash?: string
      role?: number
      status?: number
    }
    CreateUserRequest: {
      email: string
      first_name: string
      last_name: string
      date_of_birth: string
      email_verified: boolean
      phone_verified: boolean
      identity_verified: boolean
      password_hash: string
      role: number
      status: number
    }
    ErrorResponse: {
      detail?: Array<{
        msg?: string
        type?: string
      }>
    }
  }
}

export interface operations {
  get_users: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"][]
        }
      }
    }
  }
  create_user: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"]
      }
    }
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["User"]
        }
      }
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
  get_user: {
    parameters: {
      path: {
        uuid: string
      }
    }
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"]
        }
      }
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
}
